CREATE TABLE FAVORITE(
	FAVORITE_NUM INT PRIMARY KEY,					--좋아요 PK
	FAVORITE_MEMBER_ID VARCHAR(100) NOT NULL,		--좋아요 누른 사용자 FK
	FAVORITE_GYM_NUM INT NOT NULL,					--좋아요 누른 암벽장 FK
	
	CONSTRAINT FK_FAVORITE_MEMBER_ID
	FOREIGN KEY (FAVORITE_MEMBER_ID)
	REFERENCES MEMBER(MEMBER_ID)
	ON DELETE CASCADE,

	CONSTRAINT FK_FAVORITE_GYM_NUM
	FOREIGN KEY (FAVORITE_GYM_NUM)
	REFERENCES GYM(GYM_NUM)
	ON DELETE CASCADE
);
--좋아요 추가 FAVORITE_MEMBER_ID, FAVORITE_GYM_NUM
INSERT INTO FAVORITE(FAVORITE_NUM,FAVORITE_MEMBER_ID,FAVORITE_GYM_NUM)
VALUES ((SELECT NVL(MAX(FAVORITE_NUM),0)+1 FROM FAVORITE),?,?)

--좋아요 삭제 FAVORITE_MEMBER_ID, FAVORITE_GYM_NUM
DELETE FROM FAVORITE WHERE FAVORITE_MEMBER_ID = ? AND FAVORITE_GYM_NUM =?

--좋아요 찾기 FAVORITE_MEMBER_ID, FAVORITE_GYM_NUM
SELECT FAVORITE_NUM,FAVORITE_MEMBER_ID,FAVORITE_GYM_NUM FROM FAVORITE
WHERE FAVORITE_MEMBER_ID = ? AND FAVORITE_GYM_NUM =?
