CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR(100) PRIMARY KEY,						--사용자 PK
	MEMBER_NAME VARCHAR(50) NOT NULL,						--사용자 이름
	MEMBER_PASSWORD VARCHAR(100) NOT NULL,					--사용자 비밀번호
	MEMBER_PHONE VARCHAR(50) NOT NULL,						--사용자 휴대폰 번호
	MEMBER_REGISTRATION_DATE DATE DEFAULT SYSDATE,			--사용자 회원가입 날짜
	MEMBER_PROFILE VARCHAR(2048) DEFAULT 'default.jpg',		--사용자 프로필 사진
	MEMBER_CURRENT_POINT INT DEFAULT 0,						--사용자 사용가능한 포인트
	MEMBER_TOTAL_POINT INT DEFAULT 0,						--사용자 누적포인트
	MEMBER_CREW_NUM INT DEFAULT NULL,						--사용자 가입한 크루 FK
	MEMBER_CREW_JOIN_DATE DATE DEFAULT NULL,				--사용자 크루 가입한 날짜
	MEMBER_LOCATION VARCHAR(100) NOT NULL,					--사용자 지역
	MEMBER_ROLE CHAR(1) DEFAULT 'F' CHECK (MEMBER_ROLE IN ('T', 'F'))		--사용자 권한
);
--외래키 제약조건 추가
ALTER TABLE MEMBER
ADD CONSTRAINT FK_CREW_NUM
FOREIGN KEY (MEMBER_CREW_NUM)
REFERENCES CREW(CREW_NUM)
ON DELETE SET NULL;

-- 관리자 권한 추가
ALTER TABLE MEMBER
ADD MEMBER_ROLE CHAR(1) DEFAULT 'F' CHECK (MEMBER_ROLE IN ('T', 'F'));

ALTER TABLE MEMBER
MODIFY MEMBER_PROFILE DEFAULT 'default.jpg';
select * from MEMBER

--샘플데이터 작성
INSERT INTO MEMBER(MEMBER_ID,MEMBER_NAME,MEMBER_PASSWORD,MEMBER_PHONE,MEMBER_LOCATION) 
VALUES('coma2@naver.com','코마','1234','010-0000-0000','서울특별시');
INSERT INTO MEMBER(MEMBER_ID,MEMBER_NAME,MEMBER_PASSWORD,MEMBER_PHONE,MEMBER_LOCATION) 
VALUES('샘플유저2','샘플이름2','샘플비밀번호2','샘플번호2','샘플지역2');
INSERT INTO MEMBER(MEMBER_ID,MEMBER_NAME,MEMBER_PASSWORD,MEMBER_PHONE,MEMBER_LOCATION) 
VALUES('샘플유저3','샘플이름3','샘플비밀번호3','샘플번호3','샘플지역3');
INSERT INTO MEMBER(MEMBER_ID,MEMBER_NAME,MEMBER_PASSWORD,MEMBER_PHONE,MEMBER_LOCATION) 
VALUES('샘플유저4','샘플이름4','샘플비밀번호4','샘플번호4','"샘플지역4');
"샘플비밀번호5'); DROP TABLE MEMBER;--"
--ID 검색 (관리자 추가된거 확인)
SELECT MEMBER_ID,MEMBER_PASSWORD,MEMBER_NAME,MEMBER_PHONE,MEMBER_PROFILE,MEMBER_REGISTRATION_DATE,MEMBER_CURRENT_POINT,MEMBER_TOTAL_POINT,MEMBER_CREW_NUM,MEMBER_CREW_JOIN_DATE,MEMBER_LOCATION,MEMBER_ROLE
FROM MEMBER
WHERE MEMBER_ID = 'coma@naver.com';

--ID, PASSWORD 검색
SELECT MEMBER_ID,MEMBER_PASSWORD,MEMBER_NAME,MEMBER_PHONE,MEMBER_PROFILE,MEMBER_REGISTRATION_DATE,MEMBER_CURRENT_POINT,MEMBER_TOTAL_POINT,MEMBER_CREW_NUM,MEMBER_CREW_JOIN_DATE,MEMBER_LOCATION,MEMBER_ROLE
FROM MEMBER
WHERE ID = '샘플유저1' AND PASSWORD='샘플비밀번호1';
-- ' " 
--크루에 가입되지않은 유저 검색
SELECT MEMBER_ID,MEMBER_PASSWORD,MEMBER_NAME,MEMBER_PHONE,MEMBER_PROFILE,MEMBER_REGISTRATION_DATE,MEMBER_CURRENT_POINT,MEMBER_TOTAL_POINT,MEMBER_CREW_NUM,MEMBER_CREW_JOIN_DATE,MEMBER_LOCATION,MEMBER_ROLE
FROM MEMBER
WHERE CREW_ID = NULL AND ROLE='F';

--누적포인트 랭킹
SELECT MEMBER_ID,MEMBER_PASSWORD,MEMBER_NAME,MEMBER_PHONE,MEMBER_PROFILE,MEMBER_REGISTRATION_DATE,MEMBER_CURRENT_POINT,MEMBER_TOTAL_POINT,MEMBER_CREW_NUM,MEMBER_CREW_JOIN_DATE,MEMBER_LOCATION,MEMBER_ROLE
FROM MEMBER
ORDER BY MEMBER_TOTAL_POINT DESC
WHERE MEMBER_ROLE='F';

--PK로 유저 DB에서 삭제
DELETE FROM MEMBER WHERE MEMBER_ID = '샘플유저1' AND MEMBER_ID <> 'admin';

UPDATE MEMBER
SET
	MEMBER_NAME = '샘플이름1',
	MEMBER_PROFILE = NULL,
	MEMBER_PHONENUMBER = '샘플번호11',
	MEMBER_LOCATION = '샘플지역11',
	--MEMBER_CREW_NUM = 1
	--MEMBER_CREW_JOIN_DATE = SYSDATE
WHERE MEMBER_ID = '샘플유저2'

--크루가입
UPDATE MEMBER
SET
	MEMBER_CREW_NUM = 1,
	MEMBER_CREW_JOIN_DATE = SYSDATE
WHERE MEMBER_ID = 'coma@naver.com'
select * from member;
--크루 리더인지 확인
SELECT 
	M.MEMBER_NAME
FROM
	MEMBER M
JOIN
	CREW C
ON
	C.CREW_LEADER = M.MEMBER_ID
WHERE
	C.CREW_NUM = ?

--관리자 권한 변경
UPDATE MEMBER SET MEMBER_ROLE = 'T' WHERE MEMBER_ID = '샘플유저2';

--신규회원 목록 출력(7일)
SELECT MEMBER_ID,MEMBER_PASSWORD,MEMBER_NAME,MEMBER_PHONE,MEMBER_PROFILE,MEMBER_REGISTRATION_DATE,MEMBER_CURRENT_POINT,MEMBER_TOTAL_POINT,MEMBER_CREW_NUM,MEMBER_CREW_JOIN_DATE,MEMBER_LOCATION,MEMBER_ROLE
FROM member
WHERE MEMBER_REGISTRATION_DATE >= SYSDATE - INTERVAL '7' DAY AND ROLE='F';

--크루 상위 랭킹 10개
SELECT
    ROWNUM AS RANKING,
    SUB.CREW_PROFILE,
    SUB.CREW_NAME,
    MEMBER_CREW_RANK
FROM (
    SELECT
        C.CREW_PROFILE,
        C.CREW_NAME,
        SUM(M.MEMBER_TOTAL_POINT) AS MEMBER_CREW_RANK
    FROM
        MEMBER M
    JOIN
        CREW C 
    ON 
        M.MEMBER_CREW_NUM = C.CREW_NUM
    GROUP BY
        C.CREW_PROFILE,
        C.CREW_NAME
    ORDER BY
        MEMBER_CREW_RANK DESC
) SUB
WHERE ROWNUM <= 10;

--상위 개인 랭킹 10개
SELECT
    MEMBER_NAME,
    MEMBER_PROFILE
FROM (
    SELECT
        MEMBER_NAME,
        MEMBER_PROFILE
    FROM
        MEMBER
    ORDER BY
        MEMBER_TOTAL_POINT DESC
)
WHERE
    ROWNUM <= 10;

--특정 크루에 속한 사용자 이름 전부 조회 CREW_NUM
SELECT MEMBER_NAME FROM MEMBER M JOIN CREW C ON C.CREW_NUM = M.MEMBER_CREW_NUM WHERE CREW_NUM = ?

--특정 사용자가 속한 크루 찾기 MEMBER_ID
SELECT
	M.MEMBER_CREW_NUM
FROM
	MEMBER M
JOIN
	CREW C
ON
	M.MEMBER_CREW_NUM = C.CREW_NUM
WHERE
	MEMBER_ID = ?
	
-- 크루 랭킹 전체 출력
SELECT
	C.CREW_NUM,
    C.CREW_NAME,
    C.CREW_LEADER,
    C.CREW_MAX_MEMBER_SIZE,
    COUNT(M.MEMBER_ID) AS CREW_CURRENT_SIZE,
    SUM(M.MEMBER_TOTAL_POINT) AS MEMBER_TOTAL_POINT
FROM
    CREW C
JOIN
    MEMBER M 
ON 
    M.MEMBER_CREW_NUM = C.CREW_NUM
GROUP BY
	C.CREW_NUM,
    C.CREW_NAME,
    C.CREW_LEADER,
    C.CREW_MAX_MEMBER_SIZE
ORDER BY
    MEMBER_TOTAL_POINT DESC

--사용자 포인트 업데이트 MEMBER_CURRENT_POINT, MEMBER_ID
UPDATE MEMBER SET MEMBER_CURRENT_POINT = ? WHERE MEMBER_ID = ?

SELECT * FROM MEMBER;

DROP TABLE MEMBER;