CREATE TABLE REPLY (
    REPLY_NUM INT PRIMARY KEY,          -- 댓글의 고유 식별자 (기본키)
    REPLY_CONTENT VARCHAR(100) NOT NULL, -- 댓글의 내용
    REPLY_BOARD_NUM INT,         -- 댓글이 달린 게시글의 ID (외래키)
    REPLY_WRITER_ID VARCHAR(100), -- 댓글 작성자의 사용자 ID (외래키)
    -- 외래키 제약조건 설정
    CONSTRAINT FK_REPLY_BOARD_NUM 
    FOREIGN KEY (REPLY_BOARD_NUM) 
    REFERENCES BOARD(BOARD_NUM) 
    ON DELETE CASCADE,
    
    CONSTRAINT FK_REPLY_WRITER_ID
    FOREIGN KEY (REPLY_WRITER_ID)
    REFERENCES MEMBER(MEMBER_ID)
    ON DELETE CASCADE
);

--샘플데이터 INSERT
INSERT INTO REPLY (REPLY_NUM, REPLY_CONTENT, REPLY_BOARD_NUM, REPLY_WRITER_ID)
VALUES ((SELECT NVL(MAX(REPLY_NUM),0)+1 FROM REPLY), 'reply_content1', 1 ,'샘플유저1');
INSERT INTO REPLY (REPLY_NUM, REPLY_CONTENT, REPLY_BOARD_NUM, REPLY_WRITER_ID)
VALUES ((SELECT NVL(MAX(REPLY_NUM),0)+1 FROM REPLY), 'reply_content2', 2 ,'샘플유저2');
INSERT INTO REPLY (REPLY_NUM, REPLY_CONTENT, REPLY_BOARD_NUM, REPLY_WRITER_ID)
VALUES ((SELECT NVL(MAX(REPLY_NUM),0)+1 FROM REPLY), 'reply_content3', 3 ,'샘플유저3');

--댓글 삭제 DELETE
DELETE FROM REPLY WHERE REPLY_NUM=?;

--댓글 내용수정 UPDATE
UPDATE REPLY SET REPLY_CONTENT = 'reply_content3' WHERE REPLY_NUM = 2;

--댓글 선택 SELECTONE
SELECT REPLY_NUM, REPLY_BOARD_NUM, REPLY_CONTENT, REPLY_WRITER_ID FROM REPLY WHERE REPLY_NUM = 1;


--게시글에 댓글 전부 출력 SELECTALL
SELECT 
	R.REPLY_NUM, 
	R.REPLY_CONTENT,
	R.REPLY_BOARD_NUM,
	R.REPLY_WRITER_ID
FROM
	REPLY R
JOIN
	BOARD B
ON
	B.BOARD_NUM=R.REPLY_BOARD_NUM
WHERE
	REPLY_BOARD_NUM = 2;


SELECT* FROM REPLY;

DROP TABLE REPLY;